//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terrain
    {
        public Terrain()
        {
            this.Tile = new HashSet<Tile>();
        }
    
        public int TerrainID { get; set; }
        public Nullable<int> TerrainType { get; set; }
        public string TerrainName { get; set; }
        public string TerrainImage { get; set; }
    
        public virtual ICollection<Tile> Tile { get; set; }

        public Terrain(int typ, string nam, string image)
        {
            TerrainName = nam;
            TerrainType = typ;
            TerrainImage = image;
        }

    }
}
