//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Construction
    {
        public Construction()
        {
            this.Tile = new HashSet<Tile>();
            this.City = new HashSet<City>();
        }
    
        public int ConstructionID { get; set; }
        public Nullable<int> UpgradeID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string ConstructionName { get; set; }
        public Nullable<double> ConstructionEfficiency { get; set; }
        public bool ConstructionDisabled { get; set; }
        public Nullable<double> ConstructionProgress { get; set; }
    
        public virtual Unit Unit { get; set; }
        public virtual Upgrade Upgrade { get; set; }
        public virtual ICollection<Tile> Tile { get; set; }
        public virtual ICollection<City> City { get; set; }

        public Construction(string nam, double efficiency, Unit unit)
        {
            ConstructionName = nam;
            //Constructionype = typ;
            ConstructionEfficiency = efficiency;
            Unit = unit;
            ConstructionDisabled = true;
            ConstructionProgress = 0;
        }
    }
}
