//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_has_Player
    {
        public int Game_has_PlayerID { get; set; }
        public int GameID { get; set; }
        public int PlayerID { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }

        public Game_has_Player()
        {

        }

        public Game_has_Player(int gID, int pID)
        {
            GameID = gID;
            PlayerID = pID;
        }
    }
}
