//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBGame
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class G2776_2Entities1 : DbContext
    {
        public G2776_2Entities1()
            : base("name=G2776_2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Army> Army { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<Construction> Construction { get; set; }
        public DbSet<Game> Game { get; set; }
        public DbSet<Game_has_Player> Game_has_Player { get; set; }
        public DbSet<Map> Map { get; set; }
        public DbSet<Player> Player { get; set; }
        public DbSet<Terrain> Terrain { get; set; }
        public DbSet<Tile> Tile { get; set; }
        public DbSet<Unit> Unit { get; set; }
        public DbSet<UnitType> UnitType { get; set; }
        public DbSet<Upgrade> Upgrade { get; set; }
    }
}
