//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitType
    {
        public UnitType()
        {
            this.Upgrade = new HashSet<Upgrade>();
            this.Unit = new HashSet<Unit>();
        }
    
        public int UnitTypeID { get; set; }
        public string UnitTypeName { get; set; }
        public string UnitTypeDesc { get; set; }
    
        public virtual ICollection<Upgrade> Upgrade { get; set; }
        public virtual ICollection<Unit> Unit { get; set; }
    }
}
