//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upgrade
    {
        public Upgrade()
        {
            this.Construction = new HashSet<Construction>();
            this.Unit = new HashSet<Unit>();
        }
    
        public int UpgradeID { get; set; }
        public int UnitTypeID { get; set; }
        public string UpgradeName { get; set; }
    
        public virtual ICollection<Construction> Construction { get; set; }
        public virtual UnitType UnitType { get; set; }
        public virtual ICollection<Unit> Unit { get; set; }
    }
}
